version: "2"

networks:
  network_s5r:
    driver: host

volumes:
  postgres_data:

services:

  # --------------------------------------------------------------------------------------------------------------------
  # Infrastructure services
  # --------------------------------------------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer
    restart: always
    command: -d /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9099:9000"

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS="-Xms1g -Xmx1g"
      - LS_HEAP_SIZE=512m
#    networks:
#      - network_s5r

  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
#    networks:
#      - network_s5r
#    depends_on:
#      - s5r-elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
#    networks:
#      - network_s5r
#    depends_on:
#      - s5r-elasticsearch

#  s5r-consul:
#    container_name: 's5r-consul'
#    image: progrium/consul:latest
#    #command: -server -bootstrap -ui-dir /ui
#    restart: always
#    mem_limit: 128m
#    ports:
#      - 8500:8500
    #expose:
#    dns:
#      - 127.0.0.1

  # Data Storage
  # (Let's keep it very simple for now)
  s5r-mongo:
    build: mongo/
    ports:
      - "27017:27017"

  s5r-rabbitmq:
    build: rabbitmq/
    ports:
      - "8080:15672"
      - "5672:5672"

  s5r-scheduler-service:
    image: stefanwalther/sammler-scheduler-service:latest
    environment:
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@s5r-rabbitmq:5672


