version: "2"

networks:
  network_s5r:
    driver: host

volumes:
  postgres_data:

services:

  # ELK
  elasticsearch:
    container_name: "elasticsearch"
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
#    networks:
#      - network_s5r

  logstash:
    container_name: "logstash"
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
#    networks:
#      - network_s5r
#    depends_on:
#      - s5r-elasticsearch

  kibana:
    container_name: "kibana"
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
#    networks:
#      - network_s5r
#    depends_on:
#      - s5r-elasticsearch

  s5r-consul:
    container_name: 's5r-consul'
    image: progrium/consul:latest
    #command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    #expose:
#    dns:
#      - 127.0.0.1

  s5r-rabbitmq:
    container_name: 's5r-rabbitmq'
    image: rabbitmq:3.6.6-management
    ports:
      - "8080:15672"
      - "5672:5672"

  s5r-scheduler:
    container_name: 's5r-scheduler'
    image: stefanwalther/sammler-scheduler:latest
    environment:
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@s5r-rabbitmq:5672


