version: '2'
services:

  s5r-consul:
    container_name: 's5r-consul'
    image: progrium/consul:latest
    #command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    #expose:
    dns:
      - 127.0.0.1

  s5r-rabbitmq:
    container_name: 's5r-rabbitmq'
    image: rabbitmq:3.6.6-management
    ports:
      - "8080:15672"
      - "5672:5672"

  s5r-scheduler:
    container_name: 's5r-scheduler'
    image: stefanwalther/sammler-scheduler:master
    environment:
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@s5r-rabbitmq:5672
    links:
      - s5r-rabbitmq


volumes:
  postgres_data:
